docs(blog): add a resotonotebook blog post
someengineering/resoto.com pull request #163
Opened 2022-05-13 12:07 UTC by meln1k

# Description

Added a blog post about resotonotebook.

# To-Dos

- [ ] Format with `yarn format`
- [ ] Lint with `yarn lint`
- [ ] Build successfully with `yarn build`

# Issues Fixed

- Fixes #XXXX

# Code of Conduct

By submitting this pull request, I agree to follow the [code of conduct](https://resoto.com/code-of-conduct).

2022-05-26 15:50 UTC, TheCatLady requested changes

2022-05-26 15:50 UTC, TheCatLady commented on blog/2022/05-14-resotonotebook/index.md
> +Happy exploring!
```suggestion
## Next Steps

I hope this blog post has piqued your interest, and that you will try [installing Resoto Notebook](/docs/reference/notebook#installation). Happy exploring!
```

2022-05-26 15:50 UTC, TheCatLady commented on blog/2022/05-14-resotonotebook/index.md
> +Sometimes you're interested in the relationships between resources. Let's say you want to remove the database, but you're not sure which other resources this will impact. With resotonotebook, you can
```suggestion
There are instances where you may be interested in the relationships between resources. Let's say you want to remove a database, but you are not sure of the impact of the removal on other resources. With [Resoto Notebook](/docs/reference/notebook), you can inspect a resource and its relations to see what's going on.
```

2022-05-31 16:45 UTC, lloesche approved these changes

2022-05-31 16:46 UTC, merged