feat(docs): Info on how to configure additional interfaces and DNS names
someengineering/resoto.com pull request #198
Opened 2022-06-01 12:55 UTC by lloesche

# Description

Info on how to configure additional interfaces and DNS names

# Code of Conduct

By submitting this pull request, I agree to follow the [code of conduct](https://resoto.com/code-of-conduct).

2022-06-01 17:09 UTC, TheCatLady requested changes

2022-06-01 17:09 UTC, TheCatLady commented on docs/getting-started/configuring-resoto.md
> +By default Resoto tries to find all local IP addresses and hostnames and adds them to the subject alternative names (SAN) list of the x509 certificate. If the system you are running Resoto on has add
```suggestion
Resoto attempts to find all local IP addresses and hostnames and add them to the subject alternative names (SAN) list of the x509 certificate. If your system has additional DNS names, you can add them to the SAN list via the `resotocore.api.host_certificate.san_dns_names` option in the `resoto.core` configuration.
```

2022-06-01 17:09 UTC, TheCatLady commented on docs/getting-started/configuring-resoto.md
> +In `resh` enter:
```suggestion
Execute the following command in [Resoto Shell](../concepts/components/shell.md) to open the relevant configuration for editing:
```

2022-06-01 17:09 UTC, TheCatLady commented on docs/getting-started/configuring-resoto.md
> +```
````suggestion
```bash
````

2022-06-01 17:09 UTC, TheCatLady commented on docs/getting-started/configuring-resoto.md
> +[...]
```suggestion
  [...]
```

2022-06-01 17:09 UTC, TheCatLady commented on docs/getting-started/configuring-resoto.md
> +```yml title="Adding additional DNS names to the SAN list"
````suggestion
```yaml title="Resoto Core configuration with additional DNS names on SAN list"
````

2022-06-01 17:09 UTC, TheCatLady commented on docs/getting-started/installation/pip.md
> +By default `resotocore` listens on `localhost:8900`. If desired you can [make it listen on all interfaces](../configuring-resoto#make-resoto-core-listen-on-multiple-interfaces).
```suggestion
[Resoto Core](../../concepts/components/core.md) only listens on `localhost:8900` by default. [Resoto Core](../../concepts/components/core.md) can be [configured to listen on all interfaces](../configuring-resoto.md#configuring-resoto-core-network-interfaces) if desired.
```

2022-06-02 14:42 UTC, lloesche commented on docs/getting-started/configuring-resoto.md
> +```
resh is not bash, let's not use bash syntax highlighting it creates confusing visualization!

2022-06-03 16:23 UTC, TheCatLady approved these changes

2022-06-03 16:26 UTC, merged