feat(docs): Improve documentation on filtering values.
someengineering/resoto.com pull request #213
Opened 2022-06-10 13:21 UTC by aquamatthias

# Description

# To-Dos

- [ ] Format with `yarn format`
- [ ] Lint with `yarn lint`
- [ ] Build successfully with `yarn build`

# Issues Fixed

- Fixes #XXXX

# Code of Conduct

By submitting this pull request, I agree to follow the [code of conduct](https://resoto.com/code-of-conduct).

2022-06-10 14:04 UTC, meln1k submitted a review, later dismissed

2022-06-13 23:33 UTC, TheCatLady requested changes

2022-06-13 23:33 UTC, TheCatLady commented on docs/concepts/search/filters.md
> +```
````suggestion
#### Arrays

If a property is an array, specific elements can be accessed using index notation.

In the below JSON, the path `some.nested[0]` references first element of the array with path `some.nested`, and `some.nested[2]` points to the third (and last) element:

```json
{ "some": { "nested": [1, 2, 3] } }
```

In arrays of objects, object elements can also be accessed using index notation.

`some.nested[0].prop` has a value of `1` here:

```json
{ "some": { "nested": [{ "prop": 1 }, { "prop": 2 }, { "prop": 3 }] } }
```
````

2022-06-13 23:33 UTC, TheCatLady commented on docs/concepts/search/filters.md
> +In order to select elements, where the first nested prop is bigger than 2, we can use the path `some.nested[0].prop > 2`. If we want to select elements that have any nested prop bigger than 2, we can
I don't quite understand this portion. Could you clarify the meaning or give an example?

2022-06-13 23:33 UTC, TheCatLady commented on docs/concepts/search/filters.md
>  In order to access properties outside of the reported section, use the `/` syntax:
```suggestion
Most properties are defined in the `reported` section, and the CLI interprets property paths relative to the `reported` section by default. Thus, the path to property `reported.name` can simply be written as `name`.

To target properties not in the `reported` section, prefix the property path with a slash (`/`) for it to be interpreted as an absolute path:
```

2022-06-16 01:48 UTC, TheCatLady approved these changes

2022-06-16 01:50 UTC, TheCatLady commented
@aquamatthias Please see if I described the idea correctly. If so, feel free to merge!

2022-06-16 12:57 UTC, merged