feat(docs): Aws Resource Guide
someengineering/resoto.com pull request #358
Opened 2022-09-13 15:40 UTC by anjafr

# Description

Adds a section on how to contribute collecting AWS Resources

# To-Dos

- [x] Format with `yarn format`
- [x] Lint with `yarn lint`
- [x] Build successfully with `yarn build`

# Code of Conduct

By submitting this pull request, I agree to follow the [code of conduct](https://resoto.com/code-of-conduct).

2022-09-13 18:25 UTC, TheCatLady requested changes
I will also push some edits to your new doc, but here are some comments FYI

2022-09-13 18:25 UTC, TheCatLady commented on docs/contributing/plugins/index.md
> +Once the graph data is collected and sent to [Resoto Core](docs/concepts/components/core.md), the power of Resoto's [search syntax](docs/concepts/search/index.md) is at your fingertips.
```suggestion
Once the graph data is collected and sent to [Resoto Core](../../concepts/components/core.md), the power of Resoto's [search syntax](../../concepts/search/index.md) is at your fingertips.
```
Markdown links within docs pages need to be relative to the current doc.

2022-09-13 18:25 UTC, TheCatLady commented on docs/contributing/plugins/index.md
> +To test a plugin, simply launch Resoto and trigger the collect action manually by executing `workflows run collect` in the [shell](docs/concepts/components/shell.md). Once the collection is complete,
```suggestion
To test a plugin, simply launch Resoto and trigger the collect action manually by executing `workflows run collect` in the [shell](../../concepts/components/shell.md). Once the collection is complete, you execute `search (<plugin_resource_type>)` to see the newly collected resources.
```

2022-09-13 18:25 UTC, TheCatLady commented on docs/contributing/plugins/index.md
> +import { useCurrentSidebarCategory } from '@docusaurus/theme-common';
```suggestion
```

2022-09-13 18:25 UTC, TheCatLady commented on docs/contributing/plugins/index.md
> +<DocCardList items={useCurrentSidebarCategory().items}/>
```suggestion
<DocCardList />
```

2022-09-14 05:09 UTC, TheCatLady commented on docs/contributing/plugins/index.md
> +# Plugins
Need to remove this heading, restore the above frontmatter, and move the import below the "Contributing to Plugins" heading below.

2022-09-14 08:25 UTC, anjafr commented
@TheCatLady 
> I will also push some edits to your new doc, but here are some comments FYI

Please do! I have no idea what I'm doing 😆

2022-09-14 08:34 UTC, TheCatLady commented
> Please do! I have no idea what I'm doing 😆

No worries, I can take over from here :)

2022-09-16 08:59 UTC, aquamatthias approved these changes

2022-09-16 09:07 UTC, merged

2022-09-16 09:08 UTC, aquamatthias commented
Thanks! Merged the page to get the link. Please create a separate PR for any outstanding items.